### ISSUE TITLE
Wialon app bugs

### ISSUE THREAD

**Issue by astankulovmaksat** [GeekSpace-Team/WialonApp#6]
1. By default make the theme light. No need to use the system theme.
2. By default use the RU language
3. Ther is a bug when choosing the map (screenshot is attached)  
![5213418436066143167](https://github.com/user-attachments/assets/1803de93-0665-461c-83c4-b65b94769746)

4. Put the EYE near the password
5. The colour of the app, change to the colour of the logo (YTM logo green colour)
6. Everytime need to log, because when user minimize the app to the background and again expanding the app logging out (sent the video to TG)
7. User login and pass page (start page), change YTMerkezi to YTM

**Comment by kotlin-compose-multiplatform** [comment]
Fixed: By default make the theme light. No need to use the system theme.

**Comment by kotlin-compose-multiplatform** [comment]
Fixed: By default use the RU language

**Comment by kotlin-compose-multiplatform** [comment]
Fixed: The colour of the app, change to the colour of the logo (YTM logo green colour)

**Comment by kotlin-compose-multiplatform** [comment]
Fixed all @astankulovmaksat
